2023-06-19 21:51:30.329 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@7782d9d4,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:52:50.742 [http-nio-9000-exec-3] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:21.261 [http-nio-9000-exec-5] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:24.003 [http-nio-9000-exec-4] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:24.844 [http-nio-9000-exec-2] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:53:25.914 [http-nio-9000-exec-6] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:26.813 [http-nio-9000-exec-8] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:27.276 [http-nio-9000-exec-7] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:53:27.600 [http-nio-9000-exec-10] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:53:28.118 [http-nio-9000-exec-9] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:28.541 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:29.029 [http-nio-9000-exec-5] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:29.549 [http-nio-9000-exec-4] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:30.122 [http-nio-9000-exec-2] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:30.643 [http-nio-9000-exec-6] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:31.169 [http-nio-9000-exec-8] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:31.688 [http-nio-9000-exec-7] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:53:32.096 [http-nio-9000-exec-10] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:53:32.562 [http-nio-9000-exec-9] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:42.715 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:43.365 [http-nio-9000-exec-5] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:43.792 [http-nio-9000-exec-4] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:53:44.108 [http-nio-9000-exec-2] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:44.369 [http-nio-9000-exec-6] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:44.586 [http-nio-9000-exec-8] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:53:44.754 [http-nio-9000-exec-7] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:44.912 [http-nio-9000-exec-10] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:45.054 [http-nio-9000-exec-9] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:53:45.210 [http-nio-9000-exec-3] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:53:45.368 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:54:29.716 [http-nio-9000-exec-4] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:30.438 [http-nio-9000-exec-2] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:30.921 [http-nio-9000-exec-6] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:31.168 [http-nio-9000-exec-8] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:31.397 [http-nio-9000-exec-7] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:31.618 [http-nio-9000-exec-10] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:31.848 [http-nio-9000-exec-9] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin123]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:54:32.058 [http-nio-9000-exec-3] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:32.255 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:32.544 [http-nio-9000-exec-5] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin123]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:54:32.841 [http-nio-9000-exec-4] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:37.239 [http-nio-9000-exec-2] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:54:38.024 [http-nio-9000-exec-6] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:54:38.202 [http-nio-9000-exec-8] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:54:38.386 [http-nio-9000-exec-7] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:54:38.551 [http-nio-9000-exec-9] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:38.708 [http-nio-9000-exec-3] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:38.866 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:39.001 [http-nio-9000-exec-5] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:39.128 [http-nio-9000-exec-4] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:54:39.324 [http-nio-9000-exec-2] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:39.480 [http-nio-9000-exec-6] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:39.639 [http-nio-9000-exec-8] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:54:39.772 [http-nio-9000-exec-7] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:54:39.922 [http-nio-9000-exec-10] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:54:40.072 [http-nio-9000-exec-9] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:40.222 [http-nio-9000-exec-3] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:40.372 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:40.501 [http-nio-9000-exec-5] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:54:40.651 [http-nio-9000-exec-4] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:40.817 [http-nio-9000-exec-2] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:41.017 [http-nio-9000-exec-6] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:54:41.199 [http-nio-9000-exec-8] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto) with 2 errors: [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] [Field error in object 'saveUserDto' on field 'password': rejected value [admin123C]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@3f297039,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 21:55:18.442 [http-nio-9000-exec-10] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:19.836 [http-nio-9000-exec-3] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:20.516 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:21.030 [http-nio-9000-exec-5] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:21.355 [http-nio-9000-exec-4] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:21.522 [http-nio-9000-exec-2] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:21.665 [http-nio-9000-exec-6] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:21.816 [http-nio-9000-exec-8] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:21.957 [http-nio-9000-exec-7] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:22.160 [http-nio-9000-exec-10] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:22.385 [http-nio-9000-exec-9] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:22.537 [http-nio-9000-exec-3] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:22.669 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:22.804 [http-nio-9000-exec-5] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:22.948 [http-nio-9000-exec-4] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:23.091 [http-nio-9000-exec-2] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:23.248 [http-nio-9000-exec-6] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:23.382 [http-nio-9000-exec-8] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:27.766 [http-nio-9000-exec-7] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:27.910 [http-nio-9000-exec-10] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:28.052 [http-nio-9000-exec-9] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:28.210 [http-nio-9000-exec-3] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:28.338 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:28.472 [http-nio-9000-exec-5] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 21:55:28.621 [http-nio-9000-exec-2] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.create(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [0]; codes [Null.saveUserDto.id,Null.id,Null.long,Null]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id必须为null或空]] 
2023-06-19 22:13:54.803 [restartedMain] ERROR o.s.b.diagnostics.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 9000 was already in use.

Action:

Identify and stop the process that's listening on port 9000 or configure this application to listen on another port.

2023-06-19 22:17:52.614 [http-nio-9000-exec-5] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'password': rejected value [1]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@6558e4e2,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 22:17:54.427 [http-nio-9000-exec-2] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'password': rejected value [1]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@6558e4e2,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 22:17:54.998 [http-nio-9000-exec-6] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'password': rejected value [1]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@6558e4e2,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 22:17:55.462 [http-nio-9000-exec-7] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'password': rejected value [1]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@6558e4e2,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 22:18:07.083 [http-nio-9000-exec-9] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'password': rejected value [1]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@6558e4e2,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 22:18:07.997 [http-nio-9000-exec-10] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'password': rejected value [1]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@6558e4e2,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 22:18:08.512 [http-nio-9000-exec-3] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'password': rejected value [1]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@6558e4e2,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 22:18:08.873 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'password': rejected value [1]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@6558e4e2,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 22:18:09.076 [http-nio-9000-exec-4] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'password': rejected value [1]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@6558e4e2,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 22:18:09.249 [http-nio-9000-exec-5] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'password': rejected value [1]; codes [Pattern.saveUserDto.password,Pattern.password,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.password,password]; arguments []; default message [password],[Ljavax.validation.constraints.Pattern$Flag;@6558e4e2,^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[._~!@#$^&*])[A-Za-z0-9._~!@#$^&*]{8,20}$]; default message [密码不符合规范]] 
2023-06-19 22:21:37.247 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [null]; codes [NotNull.saveUserDto.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id不能为空]] 
2023-06-19 22:21:43.183 [http-nio-9000-exec-4] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [null]; codes [NotNull.saveUserDto.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id不能为空]] 
2023-06-19 22:21:43.753 [http-nio-9000-exec-3] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [null]; codes [NotNull.saveUserDto.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id不能为空]] 
2023-06-19 22:21:44.185 [http-nio-9000-exec-5] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [null]; codes [NotNull.saveUserDto.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id不能为空]] 
2023-06-19 22:22:05.731 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [null]; codes [NotNull.saveUserDto.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id不能为空]] 
2023-06-19 22:22:06.362 [http-nio-9000-exec-3] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [null]; codes [NotNull.saveUserDto.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id不能为空]] 
2023-06-19 22:22:07.202 [http-nio-9000-exec-2] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [null]; codes [NotNull.saveUserDto.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id不能为空]] 
2023-06-19 22:22:07.965 [http-nio-9000-exec-5] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [null]; codes [NotNull.saveUserDto.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id不能为空]] 
2023-06-19 22:22:08.242 [http-nio-9000-exec-4] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [null]; codes [NotNull.saveUserDto.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id不能为空]] 
2023-06-19 22:22:08.830 [http-nio-9000-exec-6] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [null]; codes [NotNull.saveUserDto.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id不能为空]] 
2023-06-19 22:23:30.972 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [null]; codes [NotNull.saveUserDto.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id不能为空]] 
2023-06-19 22:23:31.534 [http-nio-9000-exec-2] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'id': rejected value [null]; codes [NotNull.saveUserDto.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.id,id]; arguments []; default message [id]]; default message [id不能为空]] 
2023-06-19 22:24:23.873 [http-nio-9000-exec-10] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'birthday': rejected value [Sun Jul 05 09:46:39 CST 31690708]; codes [Past.saveUserDto.birthday,Past.birthday,Past.java.util.Date,Past]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.birthday,birthday]; arguments []; default message [birthday]]; default message [生日时间必须小于当前时间]] 
2023-06-19 22:24:24.684 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Validation failed for argument [0] in public com.eztech.springbase.vo.ResultVo com.eztech.springbase.controller.UserController.update(com.eztech.springbase.dto.user.SaveUserDto): [Field error in object 'saveUserDto' on field 'birthday': rejected value [Sun Jul 05 09:46:39 CST 31690708]; codes [Past.saveUserDto.birthday,Past.birthday,Past.java.util.Date,Past]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [saveUserDto.birthday,birthday]; arguments []; default message [birthday]]; default message [生日时间必须小于当前时间]] 
2023-06-19 23:24:08.634 [http-nio-9000-exec-6] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息:Required request body is missing: public com.baomidou.mybatisplus.extension.plugins.pagination.Page<com.eztech.springbase.entity.User> com.eztech.springbase.controller.UserController.page(java.lang.Integer,java.lang.Integer,java.lang.String)
2023-06-19 23:38:16.335 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息null
2023-06-19 23:38:29.153 [http-nio-9000-exec-5] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息null
2023-06-19 23:39:52.982 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息null
2023-06-19 23:41:30.038 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息null
2023-06-19 23:42:45.950 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息null
2023-06-19 23:43:27.071 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息null
2023-06-19 23:44:26.979 [http-nio-9000-exec-2] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息null
2023-06-19 23:56:46.131 [http-nio-9000-exec-1] ERROR c.e.springbase.exception.GlobalExceptionHandler - 错误信息Could not copy property 'total' from source to target; nested exception is java.lang.reflect.InvocationTargetException
